apiVersion: v1
kind: Secret
metadata:
  name: cinevision-secrets
  namespace: cinevision-dev
type: Opaque
data:
  # Base64-encoded values (echo -n "yourvalue" | base64)
  DB_USERNAME: YWRtaW4=          # admin
  DB_PASSWORD: YWRtaW4xMjM=      # admin123
  JWT_PRIVATE_KEY: "LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t..."   # truncated example
  JWT_PUBLIC_KEY: "LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0..."